"""Write REPORT.md: deliverables A-I (audit, verified results, figure inventory, verification).
Reuses the content and numbers of build_paper.py, so the report and the paper cannot disagree.

    python paper/v3/build_report.py
"""
import os, re, sys, subprocess
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_paper as B

R, ROOT = B.R, B.ROOT
B.renumber()


def md(t):
    t = re.sub(r'_\{([^}]*)\}', r'<sub>\1</sub>', t)
    return re.sub(r'\^\{([^}]*)\}', r'<sup>\1</sup>', t)


def table(cap_prefix):
    for b in B.C + B.APP:
        if b[0] == 'table' and b[1].startswith(cap_prefix):
            _, cap, head, rows, note, _ = b
            out = [f'**{md(cap)}**', '', '| ' + ' | '.join(md(h) for h in head) + ' |', '|' + '---|' * len(head)]
            out += ['| ' + ' | '.join(md(str(c)) for c in r) + ' |' for r in rows]
            if note: out += ['', '*' + md(note) + '*']
            return '\n'.join(out)
    raise KeyError(cap_prefix)


def figs():
    return [(b[1], md(b[2])) for b in B.C if b[0] == 'fig']


M, S, gp, xg, r7 = B.M, B.S, B.gp, B.xg, B.r7
larp = subprocess.run(['grep', '-rIil', r'\bLARP\b', '--exclude-dir=.git', '--exclude-dir=node_modules', '--exclude=build_report.py', '--exclude=REPORT.md', ROOT],
                      capture_output=True, text=True).stdout.split()
n_refs = len(B.REFS)
n_pages = re.search(r'Pages:\s+(\d+)', subprocess.run(['pdfinfo', R + '/Droplet_Intelligence_Paper_v3.pdf'], capture_output=True, text=True).stdout).group(1)
n_abs = len(re.sub(r'_\{|\^\{|\}', ' ', B.ABSTRACT).split())
def _text(b):
    if b[0] in ('p', 'h1', 'h2'): return b[1]
    if b[0] == 'ul': return ' '.join(b[1])
    if b[0] == 'fig': return b[2]
    if b[0] == 'table': return b[1] + ' ' + ' '.join(' '.join(map(str, r)) for r in b[3])
    return ''
alltext = ' '.join(_text(b) for b in B.C + B.APP)
cited = sorted({int(x) for m in re.finditer(r'\[(\d+(?:,\s*\d+)*)\]', alltext) for x in m.group(1).split(',')})

doc = f"""# Droplet Intelligence: reconstruction report (deliverables A–I)

This report accompanies the v3 manuscript (`Droplet_Intelligence_Paper_v3.pdf` / `.docx`, source `paper_v3.html`). It was generated by
`build_report.py` from the same result files as the paper. Anything not in the saved evidence is written as "{B.NA}".

---

## A. Project audit

### A.1 Sources audited

| Source | Content | Used for |
|---|---|---|
| `Droplet_Intelligence_v2/data/raw/01–05*.csv`, `00 - Dataset Description.pdf` | Može et al. dataset: {B.T_['rows']:,} textured + {B.RF['rows']} REF-H impacts; contact angles | all models |
| `Droplet_Intelligence_v2/data/sem_original/*.tif` (39) | JEOL SEM images, 13 surfaces × 43×/100×/350× | image reader, SEM CNN |
| `archive/v1_droplet/src/*.py` | first-phase pipeline: 13-model screen, XGBoost/GP variants M1–M6, phase 2–4 ablations, CNN, OOD | model zoo, ablations |
| `archive/v1_droplet/results/` | `zoo_table.csv`, `zoo/*_ref.npy`, `final/pred_*.npz` (per-impact ID/LOSO/REF-H), `phase2–4.json`, `phase_extra_*.json`, `final/p5–p7.json`, `cnn_*` | Tables 5–6, Fig. 3–6 |
| `Droplet_Intelligence_v2/droplet/*.py` | v2 package: data, models, benchmark, nested, export, predict, serve, sem, extensions, predict_image, video | final model, Tables 5–7 |
| `Droplet_Intelligence_v2/results/` | `benchmark.json`, `nested.json`, `loso_predictions.csv`, `refh_predictions.csv`, `sem/summary.json`, `js_parity.json`, `extensions/*`, `data_audit.json` | Tables 5–7, Fig. 4–11 |
| `Droplet_Intelligence_v2/showcase/` → `site/` | browser interface and JS engine | §13, Fig. 12, Table 7 |
| `paper/` (v2 manuscript, `ablation.json`, `by_fluid.json`) | previous paper and its ablations | Laan-only and surface-blind rows |
| `notes/`, `poster/`, `README.md`, `PROJECT_NOTES.md` | pitch, posters, summaries | context only; no numbers taken from prose |

### A.2 Datasets found
- **Used:** the Može et al. impact CSVs and the 39 SEM images (above).
- **Not usable:** the liquid-film fluorescence videos found during the video search have no drop edge, scale or frame rate, so they were excluded. No real side-view impact video of these surfaces exists in the project, and the video pipeline was tested on synthetic clips only.

### A.3 Models: validated vs proposed
- **Implemented and evaluated** (in Tables 5–6):
  - GP variants: Matérn 3/2 ARD (final), Matérn 5/2, fluid–surface interaction kernel, Laan backbone + GP residual, and a dimensional-input GP (re-run).
  - XGBoost variants M1, M2, M3, M5 and same-input XGBoost.
  - The rest of the 13-model screen: random forest, extra trees, LightGBM, CatBoost, MLP, deep ensemble, FT-Transformer, SVR, kernel ridge, kNN and quadratic ridge.
  - SEM-CNN descriptor encoder + GP; physical SEM reader + GP (image φ, image-only); wettability variants (cos θ input, Lee β<sub>0</sub>).
  - Laan law alone; surface-blind GP.
- **Proposed only** (Table 8, no results claimed): heteroscedastic GP, quantile/conformal XGBoost, wettability-aware models, temporal D(t) models, a live camera loop, and active learning.
- **"LARP":** not found anywhere in the project (files mentioning it: {len(larp)}), so it is not included.

### A.4 Old vs new
| Aspect | v1 (archive, poster) | v2 (package, previous paper) | v3 (this reconstruction) |
|---|---|---|---|
| Main metric | ID + LOSO + REF-H RMSE | LOSO with paired surface bootstrap | same, plus MAE and R² recomputed per impact |
| Model set | 13-model screen + M1–M6 | 4 GP candidates + nested selection | union of both, one table (Table 5) |
| Uncertainty | nominal + conformal multiplier | CV-calibrated q, nested coverage | same + coverage by fluid/surface (Fig. 8) |
| Surfaces from images | CNN (read REF-H as φ = {B.CNN1['REF-H']['pred'][0]:.3f}) | SEM CNN in LOSO (REF-H φ = {B.SEMGP['surface_descriptors']['REF-H']['phi']:.3f}) | + physical reader (REF-H φ = {B.IR['per_surface']['REF-H']['image_phi']:.3f}) |
| Video | – | pipeline + synthetic test | browser timing bug found and fixed |
| Dimensional inputs | phase-2 run only (0.0372) | not reported | re-run on v2 harness, CI reported |

### A.5 Problems found and how they are handled
1. **The dimensional-input GP scores lower LOSO RMSE than the final model** ({r7['loso_rmse']:.4f} vs {gp['loso']['rmse']:.4f}). Earlier drafts did not report this. The re-run confirms it, but the paired surface-bootstrap interval {B.ci(r7['delta_vs_baseline_ci95'])} includes zero. The raw encoding also needs an arbitrary REF-H code: REF-H RMSE ranges from {B.ENC['0/0']:.3f} to {B.ENC['5000/0']:.3f} depending on it. **Handling:** reported in Table 5, Table 6 and §9 as an unresolved alternative.
2. **The Laan-backbone "improvement" was significant only when replicate conditions were resampled** ({B.ci(B.CS['M6_minus_GPR_CI95'])}). With whole surfaces resampled, the interval is {B.ci(B.bd['physics_residual'])}. **Handling:** the surface result is reported.
3. **Oh redundancy.** The earlier "PIML" input set used Re, We and Oh together, but ln Oh = ½ ln We − ln Re exactly (max error {S['oh_identity_max_abs_error']:.1e}), and adding ln Oh changes LOSO by 0 to four decimals. **Handling:** explained in §2 and §9.
4. **REF-H was inspected during development.** **Handling:** it is labelled as a stress test, not blind data. It also ranks models differently from LOSO (SVR and kernel ridge do best there), so it is not used for selection.
5. **The 13-model screen saved only LOSO RMSE, not per-impact LOSO predictions.** **Handling:** LOSO MAE and R² for those models are marked n/a. Their REF-H metrics were recomputed from the saved REF-H predictions and match `zoo_table.csv`.
6. **Browser video timing bug.** Frames were indexed by list position, so dropped frames biased V (one run read 1.414 m/s against a true 1.2 m/s). **Handling:** fixed by indexing frames by media timestamps. 5/5 repeat runs now give V = {B.BVC[0]['V']:.3f} m/s.
7. **Interface label bug.** CSS uppercase turned "µm" into "MM" on two labels. **Handling:** fixed.
8. **Speculative wording in earlier text.** A physical explanation of the larger water scatter had no supporting evidence. **Handling:** replaced by the measured replicate scatter ({S['replicate_sd_by_fluid']['textured']['0']:.3f} for water vs {S['replicate_sd_by_fluid']['textured']['91']:.3f} for 91 wt%).

---

## B. Verified model-results table

{table('Table 5.')}

Per-surface RMSE for the main models:

{table('Table A1.')}

---

## C. Figure inventory

**Existing figures (before v3):**
- `paper/fig1_forest.png`, `fig2_per_surface.png`, `fig3_parity.png` and `fig4_by_fluid.png`: v2 paper.
- `Droplet_Intelligence_v2/results/evaluation.png` and `results/sem/comparison.png`.
- `archive/v1_droplet/poster/check/fig_*.png` (parity, LOSO, encoding, OOD, CNN) and `results/sem/mask_*.png`.

These are superseded by the v3 set below; each v3 figure is regenerated by `figs.py` from result files.

| v3 figure | File | Data source |
|---|---|---|
""" + '\n'.join(f"| {cap.split('.')[0]} | `figs/{fn}.png` (+ .pdf) | " + {
    'fig01_architecture': 'schematic (code structure)', 'fig02_parameter_space': 'dataset CSVs', 'fig03_model_comparison': 'verified_metrics.json',
    'fig04_parity': 'final/pred_GPR.npz, pred_XGB.npz, refh_predictions.csv', 'fig05_ablation': 'phase2–4.json, ablation.json, raw7_rerun.json, extensions',
    'fig06_importance': 'final/p6.json', 'fig07_residuals': 'final/pred_GPR.npz, benchmark.json', 'fig08_coverage': 'loso/refh_predictions.csv, nested.json',
    'fig09_error_map_uncertainty': 'pred_GPR.npz; released model (droplet.predict)', 'fig10_sem_image_reader': 'SEM TIFFs, extensions/summary.json',
    'fig11_video_pipeline': 'synthetic_video.render + video.analyse', 'fig12_interface': 'screenshots of site/ (screenshots.py)'}[fn] + ' |' for fn, cap in figs()) + f"""

---

## D. Complete paper
- `paper/v3/Droplet_Intelligence_Paper_v3.pdf` (A4, {n_pages} pages), `Droplet_Intelligence_Paper_v3.docx` and `paper_v3.html`.
- Structure: title, abstract ({n_abs} words), keywords, Sections 1–16, acknowledgements, data availability, {n_refs} references, Appendices A–C.

## E. Model-comparison section
Sections 7 and 8 of the paper. In short:
- **GP vs XGBoost:** the GP beats XGBoost on unseen surfaces (Δ {B.ci(S['delta_vs_GP_ci95']['XGB'])}, GP better on {B.GX['GPR_wins_surfaces']}/12 surfaces).
- **Why the GP wins:** it suits a small, smooth problem, gives a native posterior variance, and degrades gracefully at the edge of the descriptor range.
- **Why XGBoost loses ground:** it captures interactions but has no native uncertainty and extrapolates as a constant.
- **Role of the CNN:** it is a descriptor reader that complements the GP, not a competing β<sub>max</sub> predictor.

## F. Updated plots
Twelve figures in `paper/v3/figs/` (PNG at 300 dpi and vector PDF), listed in C.

## G. Limitations
Section 15 of the paper (10 items). The most important:
- 12 surfaces from one laboratory.
- Wide bootstrap intervals.
- REF-H was not blind.
- Under-coverage for low-viscosity fluids.
- Video tested on synthetic clips only.

## H. Appendix
- Appendix A of the paper: per-surface RMSE.
- Appendix B: reproducibility.
- Appendix C: verification.
- Hyperparameters are in Table 4 and the contribution table is Table 1.

{table('Table B1.')}

---

## I. Final verification report

| Check | Result |
|---|---|
| Fabricated values | **NONE.** Every number in the paper and this report is read from a saved result file or recomputed from saved per-impact predictions at build time (`collect_metrics.py`, `stats.py`, `build_paper.py`) |
| Unverified models in results tables | **NONE.** Planned work is only in Table 8 |
| "LARP" or other unverified model | **NOT INCLUDED** (no occurrence in the project) |
| Metrics recomputed vs saved values | GP LOSO RMSE {gp['loso']['rmse']:.8f} (v1 per-impact) vs {M['v2_baseline']['loso']['rmse']:.8f} (v2 re-implementation); all 13 zoo REF-H RMSEs recomputed and equal to `zoo_table.csv` |
| Re-runs in this study | dimensional-input GP ({r7['loso_rmse']:.4f}, matches archived 0.0372); bootstrap CIs; latency; synthetic video (Python and browser) |
| Latency claims | measured: Python {S['latency_python_single_query_ms']['median']:.1f} ms, browser {B.BL['median_ms']:.1f} ms median per prediction; **no** camera-to-result real-time claim |
| References | {n_refs} entries, all cited ({', '.join(map(str, cited))}); standard published works; none invented |
| Values marked "{B.NA}" | ID metrics of v2 GP variants; LOSO MAE/R² of the 13-model screen; REF-H MAE/R² of the dimensional GP; accuracy of the video pipeline on real footage; live-camera latency |
| Website role | Confined to §13 and Fig. 12; no accuracy claim depends on it |
"""
open(R + '/REPORT.md', 'w').write(doc)
print('wrote REPORT.md', len(doc.split()), 'words')
